/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattleshipRouteImport } from './routes/battleship'
import { Route as SwitcherooRouteImport } from './routes/switcheroo'
import { Route as TreasureRouteImport } from './routes/treasure'
import { Route as PlayCodeRouteImport } from './routes/play.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleshipRoute = BattleshipRouteImport.update({
  id: '/battleship',
  path: '/battleship',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitcherooRoute = SwitcherooRouteImport.update({
  id: '/switcheroo',
  path: '/switcheroo',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasureRoute = TreasureRouteImport.update({
  id: '/treasure',
  path: '/treasure',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battleship': typeof BattleshipRoute
  '/switcheroo': typeof SwitcherooRoute
  '/treasure': typeof TreasureRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battleship': typeof BattleshipRoute
  '/switcheroo': typeof SwitcherooRoute
  '/treasure': typeof TreasureRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battleship': typeof BattleshipRoute
  '/switcheroo': typeof SwitcherooRoute
  '/treasure': typeof TreasureRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battleship' | '/switcheroo' | '/treasure' | '/play/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battleship' | '/switcheroo' | '/treasure' | '/play/$code'
  id:
    | '__root__'
    | '/'
    | '/battleship'
    | '/switcheroo'
    | '/treasure'
    | '/play/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleshipRoute: typeof BattleshipRoute
  SwitcherooRoute: typeof SwitcherooRoute
  TreasureRoute: typeof TreasureRoute
  PlayCodeRoute: typeof PlayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battleship': {
      id: '/battleship'
      path: '/battleship'
      fullPath: '/battleship'
      preLoaderRoute: typeof BattleshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switcheroo': {
      id: '/switcheroo'
      path: '/switcheroo'
      fullPath: '/switcheroo'
      preLoaderRoute: typeof SwitcherooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasure': {
      id: '/treasure'
      path: '/treasure'
      fullPath: '/treasure'
      preLoaderRoute: typeof TreasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleshipRoute: BattleshipRoute,
  SwitcherooRoute: SwitcherooRoute,
  TreasureRoute: TreasureRoute,
  PlayCodeRoute: PlayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
